## Configuration for the training, evaluation
samples:

  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_1MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_2MeV.h5
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_3MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_4MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_5MeV.h5
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_6MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_7MeV.h5
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_8MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_9MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_10MeV.h5
    xsec: 1
    ngen: 1  

#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_20MeV.h5
#     xsec: 1
#     ngen: 1  
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_30MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_40MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_50MeV.h5
#     xsec: 1
#     ngen: 1  
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_60MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_70MeV.h5
#     xsec: 1
#     ngen: 1  
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_80MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_90MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_100MeV.h5
#     xsec: 1
#     ngen: 1  
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_110MeV.h5
#     xsec: 1
#     ngen: 1  

#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_120MeV.h5
#     xsec: 1
#     ngen: 1  
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_130MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_140MeV.h5
#     xsec: 1
#     ngen: 1
#   - name: jsns2_vertex
#     label: 1
#     path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230720/combined_150MeV.h5
#     xsec: 1
#     ngen: 1  
training:
    randomSeed1: 12345
    nDataLoaders: 16

    splitFractions: [0.8, 0.1] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-3
