## Configuration for the training, evaluation
samples:

  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_1MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_2MeV.h5
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_3MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_4MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_5MeV.h5
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_6MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_7MeV.h5
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_8MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_9MeV.h5
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_0324/combined_10MeV.h5
    xsec: 1
    ngen: 1  


training:
    randomSeed1: 12345
    nDataLoaders: 2

    splitFractions: [0.8, 0.1] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-3
