## Configuration for the training, evaluation
samples:

  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_1MeV.pt
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_2MeV.pt
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_3MeV.pt
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_4MeV.pt
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_5MeV.pt
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_6MeV.pt
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_7MeV.pt
    xsec: 1
    ngen: 1  
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_8MeV.pt
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_9MeV.pt
    xsec: 1
    ngen: 1
  - name: jsns2_vertex
    label: 1
    path: /users/yewzzang/work/JSNS2_data_processing/analysis/mc_data_20230817_1000k/combined_10MeV.pt
    xsec: 1
    ngen: 1  


training:
    randomSeed1: 12345
    nDataLoaders: 16

    splitFractions: [0.7, 0.2] ## training set, validation set. (test set is the reminders)

    epoch: 400
    learningRate: 1e-3
